Author.create(name: 'J. K. Rowling', description: 'Joanne Rowling CH OBE FRSL, also known by her pen name J. K. Rowling, is a British author and philanthropist. She wrote Harry Potter, a seven-volume childrens fantasy series published from 1997 to 2007')
Author.create(name: 'George R. R. Martin', description: 'George Raymond Richard Martin, also known as GRRM, is an American novelist, screenwriter, television producer and short story writer.')
Author.create(name: 'C. S. Lewis', description: 'Clive Staples Lewis was a British writer and Anglican lay theologian. He held academic positions in English literature at both Oxford University and Cambridge University.')
Author.create(name: 'Tom Clancy', description: 'Thomas Leo Clancy Jr. was an American novelist. He is best known for his technically detailed espionage and military-science storylines set during and after the Cold War. Seventeen of his novels have been bestsellers and more than 100 million copies of his books have been sold.')
Author.create(name: 'Andrzej Sapkowski', description: 'Andrzej Sapkowski is a Polish fantasy writer, essayist, translator and a trained economist. He is best known for his six-volume series of books The Witcher, which revolves around the eponymous witcher, a monster-hunter, Geralt of Rivia.')

Book.create(author_id: 1, name: 'Harry Potter and the Philosophers Stone', description: 'Harry Potter and the Philosophers Stone is a 1997 fantasy novel written by British author J. K. Rowling.')
Book.create(author_id: 1, name: 'Harry Potter and the Chamber of Secrets', description: 'Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling and the second novel in the Harry Potter series.')
Book.create(author_id: 1, name: 'Harry Potter and the Prisoner of Azkaban', description: 'Harry Potter and the Prisoner of Azkaban is a fantasy novel written by British author J. K. Rowling and is the third in the Harry Potter series. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry.')

Book.create(author_id: 2, name: 'A Game of Thrones', description: 'A Game of Thrones is the first novel in A Song of Ice and Fire, a series of fantasy novels by American author George R. R. Martin. It was first published on August 1, 1996. The novel won the 1997 Locus Award and was nominated for both the 1997 Nebula Award and the 1997 World Fantasy Award.')
Book.create(author_id: 2, name: 'A Clash of Kings', description: 'A Clash of Kings is the second of seven planned novels in A Song of Ice and Fire, an epic fantasy series by American author George R. R. Martin. It was first published on November 16, 1998 in the United Kingdom; the first United States edition followed on February 2, 1999.')
Book.create(author_id: 2, name: 'A Storm of Swords', description: 'A Storm of Swords is the third of seven planned novels in A Song of Ice and Fire, a fantasy series by American author George R. R. Martin. It was first published on August 8, 2000, in the United Kingdom, with a United States edition following in November 2000.')

Book.create(author_id: 3, name: 'The Magicians Nephew', description: 'The Magicians Nephew is a fantasy childrens novel by C. S. Lewis, published in 1955 by The Bodley Head. It is the sixth published of seven novels in The Chronicles of Narnia. In recent editions, which sequence the books according to Narnia history, it is volume one of the series.')
Book.create(author_id: 3, name: 'The Lion, the Witch and the Wardrobe', description: 'The Lion, the Witch and the Wardrobe is a fantasy novel for children by C. S. Lewis, published by Geoffrey Bles in 1950. It is the first published and best known of seven novels in The Chronicles of Narnia. Among all the authors books, it is also the most widely held in libraries.')
Book.create(author_id: 3, name: 'The Horse and His Boy', description: 'The Horse and His Boy is a novel for children by C. S. Lewis, published by Geoffrey Bles in 1954. Of the seven novels that comprise The Chronicles of Narnia, The Horse and His Boy was the fifth to be published.')

Book.create(author_id: 4, name: 'Rainbow Six', description: 'Rainbow Six is a techno-thriller novel, written by Tom Clancy and released on August 3, 1998. It is the second book to primarily focus on John Clark, one of the recurring characters in the Ryanverse, after Without Remorse; it also features his son-in-law Domingo "Ding" Chavez.')
Book.create(author_id: 4, name: 'Splinter Cell', description: 'In response to the growing use of sophisticated digital encryption to conceal potential threats to the United States, the National Security Agency has ushered forth the new dawn of intelligence-gathering techniques. The top-secret initiative is dubbed Third Echelon.')
Book.create(author_id: 4, name: 'Clear and Present Danger', description: 'Clear and Present Danger is a political thriller novel, written by Tom Clancy and published on August 17, 1989.')

Book.create(author_id: 5, name: 'The Last Wish', description: 'The Last Wish is the second published of the two collections of short stories preceding the main Witcher Saga, written by Polish fantasy writer Andrzej Sapkowski. The first Polish edition was published in 1993 and the first English edition was first published on 7 June 2007.')
Book.create(author_id: 5, name: 'Blood of Elves', description: 'Blood of Elves is the first novel in The Witcher series written by the Polish fantasy writer Andrzej Sapkowski, first published in Poland in 1994. It is a sequel to the Witcher short stories collected in the books The Last Wish and Sword of Destiny and is followed by Time of Contempt.')
Book.create(author_id: 5, name: 'Time of Contempt', description: 'Time of Contempt is the second novel in the Witcher Saga written by Polish fantasy writer Andrzej Sapkowski, first published 1995 in Polish, and 2013 in English. It is a sequel to the first Witcher novel Blood of Elves and is followed by Baptism of Fire.')

